import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { WorldBox, WorldHull, WorldModel } from "@mechfall/shared";

const MAX_MODEL_BYTES = 64 * 1024 * 1024;
const HEX_COLOR = /^#[0-9a-f]{6}$/i;

export interface PublishMapResult {
  mapName: string;
  mapCodePath: string;
}

export interface PublishedMapModel {
  url: string;
  modelPath: string;
}

export async function publishMapModel(
  workspaceRoot: string,
  mapNameValue: unknown,
  fileNameValue: unknown,
  bytes: Buffer
): Promise<PublishedMapModel> {
  const mapName = requireString(mapNameValue, "map name", 60);
  const originalName = requireString(fileNameValue, "model file name", 180);
  const extension = path.extname(originalName).toLowerCase();
  if (extension !== ".glb" && extension !== ".gltf") throw new Error("The active model must be a .glb or .gltf file.");
  validateModelBytes(extension, bytes);
  const publicName = `${slugify(mapName)}${extension}`;
  const modelsDirectory = path.join(workspaceRoot, "client", "public", "models", "maps");
  await mkdir(modelsDirectory, { recursive: true });
  const modelPath = path.join(modelsDirectory, publicName);
  await writeFile(modelPath, bytes);
  return { url: `/models/maps/${publicName}`, modelPath };
}

export async function publishMapToGame(workspaceRoot: string, value: unknown): Promise<PublishMapResult> {
  const payload = requireRecord(value, "map payload");
  const mapName = requireString(payload.mapName, "map name", 60);
  const worldSize = requireNumber(payload.worldSize, "world size", 8, 120);
  const floorColor = requireColor(payload.floorColor, "floor color");
  const borderColor = requireColor(payload.borderColor, "border color");
  const boxes = requireBoxes(payload.boxes);
  const hulls = requireHulls(payload.hulls);
  let worldModel: WorldModel | undefined;
  if (payload.model !== undefined && payload.model !== null) {
    const model = requireRecord(payload.model, "model");
    const url = requireString(model.url, "model URL", 240);
    if (!/^\/models\/maps\/[a-z0-9][a-z0-9._-]*\.(?:glb|gltf)$/i.test(url)) throw new Error("The model was not uploaded to the game map folder.");
    const transform = requireRecord(model.transform, "model transform");
    worldModel = {
      url,
      position: requireTuple(transform.position, "model position"),
      rotation: requireTuple(transform.rotation, "model rotation"),
      scale: requirePositiveTuple(transform.scale, "model scale")
    };
  }

  const generatedSource = makeGeneratedWorldSource({ mapName, worldSize, floorColor, borderColor, boxes, hulls, worldModel }, "../world.ts");
  const mapsDirectory = path.join(workspaceRoot, "shared", "src", "game", "maps");
  await mkdir(mapsDirectory, { recursive: true });
  const mapCodePath = path.join(mapsDirectory, `${slugify(mapName)}.ts`);
  await writeFile(mapCodePath, generatedSource, "utf8");
  const activeMapPath = path.join(workspaceRoot, "shared", "src", "game", "generatedWorld.ts");
  await writeFile(activeMapPath, `/** Active map selected by the map maker. */\nexport * from "./maps/${slugify(mapName)}.ts";\n`, "utf8");
  return { mapName, mapCodePath };
}

function validateModelBytes(extension: string, bytes: Buffer): void {
  if (!bytes.length || bytes.length > MAX_MODEL_BYTES) throw new Error("The model file is empty or larger than 64 MB.");
  if (extension === ".glb" && bytes.subarray(0, 4).toString("ascii") !== "glTF") throw new Error("The selected .glb file is invalid.");
  if (extension === ".gltf") {
    try {
      JSON.parse(bytes.toString("utf8"));
    } catch {
      throw new Error("The selected .gltf file is invalid.");
    }
  }
}

function makeGeneratedWorldSource(input: {
  mapName: string;
  worldSize: number;
  floorColor: string;
  borderColor: string;
  boxes: WorldBox[];
  hulls: WorldHull[];
  worldModel?: WorldModel;
}, worldImportPath: string): string {
  const model = input.worldModel ? JSON.stringify(input.worldModel, null, 2) : "undefined";
  return `import type { WorldBox, WorldHull, WorldModel } from ${JSON.stringify(worldImportPath)};\n\n`
    + `/** Generated by the map maker. Use ADD TO GAME instead of editing this file by hand. */\n`
    + `export const GENERATED_WORLD_NAME = ${JSON.stringify(input.mapName)};\n`
    + `export const GENERATED_WORLD_SIZE = ${input.worldSize};\n`
    + `export const GENERATED_FLOOR_COLOR = ${JSON.stringify(input.floorColor)};\n`
    + `export const GENERATED_BORDER_COLOR = ${JSON.stringify(input.borderColor)};\n`
    + `export const GENERATED_WORLD_MODEL: WorldModel | undefined = ${model};\n\n`
    + `export const GENERATED_WORLD_BOXES: readonly WorldBox[] = ${JSON.stringify(input.boxes, null, 2)};\n\n`
    + `export const GENERATED_WORLD_HULLS: readonly WorldHull[] = ${JSON.stringify(input.hulls, null, 2)};\n`;
}

function requireBoxes(value: unknown): WorldBox[] {
  if (!Array.isArray(value) || value.length > 2_000) throw new Error("The map must contain at most 2,000 collision boxes.");
  return value.map((item, index) => {
    const box = requireRecord(item, `box ${index + 1}`);
    const kind = box.kind;
    if (!(["wall", "crate", "table", "column", "planter"] as unknown[]).includes(kind)) throw new Error(`Box ${index + 1} has an invalid kind.`);
    return {
      id: requireString(box.id, `box ${index + 1} id`, 100),
      position: requireTuple(box.position, `box ${index + 1} position`),
      size: requirePositiveTuple(box.size, `box ${index + 1} size`),
      color: requireColor(box.color, `box ${index + 1} color`),
      kind: kind as WorldBox["kind"],
      solid: box.solid !== false
    };
  });
}

function requireHulls(value: unknown): WorldHull[] {
  if (!Array.isArray(value) || value.length > 200) throw new Error("The map must contain at most 200 collision meshes.");
  let totalVertices = 0;
  let totalTriangles = 0;
  return value.map((item, index) => {
    const hull = requireRecord(item, `collision mesh ${index + 1}`);
    if (!Array.isArray(hull.vertices) || !Array.isArray(hull.triangles)) throw new Error(`Collision mesh ${index + 1} is missing geometry.`);
    const vertices = hull.vertices.map((vertex, vertexIndex) => requireTuple(vertex, `collision mesh ${index + 1} vertex ${vertexIndex + 1}`));
    if (vertices.length < 4 || hull.triangles.length < 1) throw new Error(`Collision mesh ${index + 1} does not contain enough geometry.`);
    const triangles = hull.triangles.map((triangle, triangleIndex) => {
      const tuple = requireTuple(triangle, `collision mesh ${index + 1} triangle ${triangleIndex + 1}`);
      const result = tuple.map(Math.trunc) as [number, number, number];
      if (result.some((vertex) => vertex < 0 || vertex >= vertices.length)) throw new Error(`Collision mesh ${index + 1} has an invalid triangle.`);
      return result;
    });
    totalVertices += vertices.length;
    totalTriangles += triangles.length;
    if (totalVertices > 100_000 || totalTriangles > 100_000) throw new Error("The map collision is too detailed to add to the game.");
    return {
      id: requireString(hull.id, `collision mesh ${index + 1} id`, 100),
      vertices,
      triangles,
      color: requireColor(hull.color, `collision mesh ${index + 1} color`),
      kind: "hull",
      solid: hull.solid !== false,
      visible: hull.visible !== false
    };
  });
}

function requireRecord(value: unknown, label: string): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`Invalid ${label}.`);
  return value as Record<string, unknown>;
}

function requireString(value: unknown, label: string, maxLength: number): string {
  if (typeof value !== "string" || !value.trim() || value.length > maxLength) throw new Error(`Invalid ${label}.`);
  return value.trim();
}

function requireColor(value: unknown, label: string): string {
  const color = requireString(value, label, 7);
  if (!HEX_COLOR.test(color)) throw new Error(`Invalid ${label}.`);
  return color.toLowerCase();
}

function requireNumber(value: unknown, label: string, minimum: number, maximum = Number.MAX_SAFE_INTEGER): number {
  const number = Number(value);
  if (!Number.isFinite(number) || number < minimum || number > maximum) throw new Error(`Invalid ${label}.`);
  return number;
}

function requireTuple(value: unknown, label: string): [number, number, number] {
  if (!Array.isArray(value) || value.length !== 3) throw new Error(`Invalid ${label}.`);
  return value.map((item) => requireNumber(item, label, -1_000_000, 1_000_000)) as [number, number, number];
}

function requirePositiveTuple(value: unknown, label: string): [number, number, number] {
  if (!Array.isArray(value) || value.length !== 3) throw new Error(`Invalid ${label}.`);
  return value.map((item) => requireNumber(item, label, 0.0001, 1_000_000)) as [number, number, number];
}

function slugify(value: string): string {
  return value.normalize("NFKD").replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase() || "map";
}
